### 주문 요청 초기 저장
POST http://localhost:8000/api/v1/orders/init
Content-Type: application/json

{
  "userId": "7",
  "payMethod": "CARD",
  "receiverName": "정선주",
  "receiverPhone": "01000001234",
  "receiverZipcode": "12345",
  "receiverAddress1": "서울시 송파구",
  "receiverAddress2": "우리집",
  "etcMessage": "감사합니다",
  "orderItemList": [
    {
      "orderCount": 2,
      "itemToken": "item_yuAzfZSNySTHIZRwRYxe",
      "itemName": "원피스",
      "itemPrice": "50000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "MEDIUM",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "RED",
              "itemOptionPrice": 0
            }
          ]
        }
      ]
    },
    {
      "orderCount": 1,
      "itemToken": "item_VxQylTtlXEPvewrUhkpr",
      "itemName": "목걸이",
      "itemPrice": "70000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "종류",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "GOLD",
              "itemOptionPrice": 10000
            }
          ]
        }
      ]
    }
  ]
}

### 주문 결제 처리
POST http://localhost:8000/api/v1/orders/payment-order
Content-Type: application/json

{
  "orderToken": "ord_TIYDORKJyKEefNBnFoGf",
  "payMethod": "CARD",
  "amount": "180000",
  "orderDescription": "주문테스트"
}

### 주문 조회
GET http://localhost:8000/api/v1/orders/ord_TIYDORKJyKEefNBnFoGf